### ISSUE TITLE
本地运行出错 主机arch

### ISSUE THREAD

**Issue by marklove5102** [zmrenwu/django-blog-project#7]
[arch@archlinux django-blog-project]$ sudo docker-compose -f local.yml up --build
[sudo] arch 的密码：
Creating network "django-blog-project_default" with the default driver
Building blogproject_local
Step 1/13 : FROM python:3.6-alpine
3.6-alpine: Pulling from library/python
df20fa9351a1: Pull complete
36b3adc4ff6f: Pull complete
8ad3a11d3b57: Pull complete
46f8f816bc3b: Pull complete
0dadc02b9964: Pull complete
Digest: sha256:1aecd84e20860196525570a6cdc6016c2954ed241b1d254c0af3348382734082
Status: Downloaded newer image for python:3.6-alpine
 ---> 96b6b6d94572
Step 2/13 : ENV PYTHONUNBUFFERED 1
 ---> Running in 18c8e29777fd
Removing intermediate container 18c8e29777fd
 ---> f435a0e3bc9e
Step 3/13 : RUN apk update   && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev gcc   && apk add gettext
 ---> Running in accfa090101b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.0-283-g612cd12ab6 [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.0-276-gbdd3966958 [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12747 distinct packages available
(1/68) Installing brotli-libs (1.0.7-r5)
(2/68) Installing libpng (1.6.37-r1)
(3/68) Installing freetype (2.10.2-r0)
(4/68) Installing pkgconf (1.7.2-r0)
(5/68) Installing brotli-dev (1.0.7-r5)
(6/68) Installing zlib-dev (1.2.11-r3)
(7/68) Installing libpng-dev (1.6.37-r1)
(8/68) Installing freetype-dev (2.10.2-r0)
(9/68) Installing libgcc (9.3.0-r2)
(10/68) Installing libstdc++ (9.3.0-r2)
(11/68) Installing binutils (2.34-r1)
(12/68) Installing gmp (6.2.0-r0)
(13/68) Installing isl (0.18-r0)
(14/68) Installing libgomp (9.3.0-r2)
(15/68) Installing libatomic (9.3.0-r2)
(16/68) Installing libgphobos (9.3.0-r2)
(17/68) Installing mpfr4 (4.0.2-r4)
(18/68) Installing mpc1 (1.1.0-r1)
(19/68) Installing gcc (9.3.0-r2)
(20/68) Installing libjpeg-turbo (2.0.5-r0)
(21/68) Installing libjpeg-turbo-dev (2.0.5-r0)
(22/68) Installing jpeg-dev (9d-r0)
(23/68) Installing tiff (4.1.0-r0)
(24/68) Installing libtiffxx (4.1.0-r0)
(25/68) Installing tiff-dev (4.1.0-r0)
(26/68) Installing lcms2 (2.9-r1)
(27/68) Installing lcms2-dev (2.9-r1)
(28/68) Installing openjpeg (2.3.1-r4)
(29/68) Installing openjpeg-dev (2.3.1-r4)
(30/68) Installing tcl (8.6.10-r0)
(31/68) Installing tcl-dev (8.6.10-r0)
(32/68) Installing libxau (1.0.9-r0)
(33/68) Installing xorgproto (2020.1-r0)
(34/68) Installing libxau-dev (1.0.9-r0)
(35/68) Installing xcb-proto (1.14-r0)
(36/68) Installing libbsd (0.10.0-r0)
(37/68) Installing libxdmcp (1.1.3-r0)
(38/68) Installing libxcb (1.14-r1)
(39/68) Installing libxdmcp-dev (1.1.3-r0)
(40/68) Installing libxcb-dev (1.14-r1)
(41/68) Installing xtrans (1.4.0-r1)
(42/68) Installing libx11 (1.6.12-r0)
(43/68) Installing libx11-dev (1.6.12-r0)
(44/68) Installing libxrender (0.9.10-r3)
(45/68) Installing libuuid (2.35.2-r0)
(46/68) Installing fontconfig (2.13.1-r2)
(47/68) Installing libxft (2.3.3-r0)
(48/68) Installing expat-dev (2.2.9-r1)
(49/68) Installing libblkid (2.35.2-r0)
(50/68) Installing blkid (2.35.2-r0)
(51/68) Installing libcap-ng (0.7.10-r1)
(52/68) Installing setpriv (2.35.2-r0)
(53/68) Installing libmount (2.35.2-r0)
(54/68) Installing libsmartcols (2.35.2-r0)
(55/68) Installing findmnt (2.35.2-r0)
(56/68) Installing mcookie (2.35.2-r0)
(57/68) Installing hexdump (2.35.2-r0)
(58/68) Installing lsblk (2.35.2-r0)
(59/68) Installing libfdisk (2.35.2-r0)
(60/68) Installing sfdisk (2.35.2-r0)
(61/68) Installing cfdisk (2.35.2-r0)
(62/68) Installing util-linux (2.35.2-r0)
(63/68) Installing util-linux-dev (2.35.2-r0)
(64/68) Installing fontconfig-dev (2.13.1-r2)
(65/68) Installing libxrender-dev (0.9.10-r3)
(66/68) Installing libxft-dev (2.3.3-r0)
(67/68) Installing tk (8.6.10-r1)
(68/68) Installing tk-dev (8.6.10-r1)
Executing busybox-1.31.1-r16.trigger
OK: 173 MiB in 102 packages
(1/4) Installing libunistring (0.9.10-r0)
(2/4) Installing gettext-libs (0.20.2-r0)
(3/4) Installing libxml2 (2.9.10-r4)
(4/4) Installing gettext (0.20.2-r0)
Executing busybox-1.31.1-r16.trigger
OK: 178 MiB in 106 packages
Removing intermediate container accfa090101b
 ---> 558897fed9cc
Step 4/13 : RUN apk add musl-dev
 ---> Running in 690cc9c823c7
(1/1) Installing musl-dev (1.1.24-r9)
OK: 189 MiB in 107 packages
Removing intermediate container 690cc9c823c7
 ---> 809bbb60beed
Step 5/13 : WORKDIR /app
 ---> Running in 1495d600c6e5
Removing intermediate container 1495d600c6e5
 ---> 1f04feca8c2d
Step 6/13 : RUN pip3 install pip --upgrade -i https://pypi.douban.com/simple
 ---> Running in 6f5666081d58
Looking in indexes: https://pypi.douban.com/simple
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (20.2.2)
Removing intermediate container 6f5666081d58
 ---> eb5adf790f16
Step 7/13 : RUN pip3 install pipenv -i https://pypi.douban.com/simple
 ---> Running in 1dd8ab967ed4
Looking in indexes: https://pypi.douban.com/simple
Collecting pipenv
  Downloading https://pypi.doubanio.com/packages/8b/02/cf3cb144314f56eaf388a83bcf481a3200c9df46ca6ceeecfb6eb4be155a/pipenv-2020.8.13-py2.py3-none-any.whl (3.9 MB)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (49.6.0)
Collecting certifi
  Downloading https://pypi.doubanio.com/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Requirement already satisfied: pip>=18.0 in /usr/local/lib/python3.6/site-packages (from pipenv) (20.2.2)
Collecting virtualenv-clone>=0.2.5
  Downloading https://pypi.doubanio.com/packages/83/b8/cd931487d250565392c39409117436d910232c8a3ac09ea2fb62a6c47bff/virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
Collecting virtualenv
  Downloading https://pypi.doubanio.com/packages/12/51/36c685ff2c1b2f7b4b5db29f3153159102ae0e0adaff3a26fd1448232e06/virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
Collecting appdirs<2,>=1.4.3
  Downloading https://pypi.doubanio.com/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting filelock<4,>=3.0.0
  Downloading https://pypi.doubanio.com/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting importlib-resources>=1.0; python_version < "3.7"
  Downloading https://pypi.doubanio.com/packages/ba/03/0f9595c0c2ef12590877f3c47e5f579759ce5caf817f8256d5dcbd8a1177/importlib_resources-3.0.0-py2.py3-none-any.whl (23 kB)
Collecting distlib<1,>=0.3.1
  Downloading https://pypi.doubanio.com/packages/f5/0a/490fa011d699bb5a5f3a0cf57de82237f52a6db9d40f33c53b2736c9a1f9/distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting importlib-metadata<2,>=0.12; python_version < "3.8"
  Downloading https://pypi.doubanio.com/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting six<2,>=1.9.0
  Downloading https://pypi.doubanio.com/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.4; python_version < "3.8"
  Downloading https://pypi.doubanio.com/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: certifi, virtualenv-clone, appdirs, filelock, zipp, importlib-resources, distlib, importlib-metadata, six, virtualenv, pipenv
Successfully installed appdirs-1.4.4 certifi-2020.6.20 distlib-0.3.1 filelock-3.0.12 importlib-metadata-1.7.0 importlib-resources-3.0.0 pipenv-2020.8.13 six-1.15.0 virtualenv-20.0.31 virtualenv-clone-0.5.4 zipp-3.1.0
Removing intermediate container 1dd8ab967ed4
 ---> e958d672b0e1
Step 8/13 : COPY Pipfile /app/Pipfile
 ---> 8e46d5a84c09
Step 9/13 : COPY Pipfile.lock /app/Pipfile.lock
 ---> fc7dbc185057
Step 10/13 : RUN pipenv install --system --dev --ignore-pipfile
 ---> Running in 37475710b843
Installing dependencies from Pipfile.lock (0b6c22)…
Looking in indexes: https://pypi.org/simple/
Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
An error occurred while installing bcrypt==3.1.7 --hash=sha256:d7bdc26475679dd073ba0ed2766445bb5b20ca4793ca0db32b399dccc6bc84b7 --hash=sha256:6305557019906466fc42dbc53b46da004e72fd7a551c044a827e572c82191752 --hash=sha256:8b10acde4e1919d6015e1df86d4c217d3b5b01bb7744c36113ea43d529e1c3de --hash=sha256:0258f143f3de96b7c14f762c770f5fc56ccd72f8a1857a451c1cd9a655d9ac89 --hash=sha256:ce4e4f0deb51d38b1611a27f330426154f2980e66582dc5f438aad38b5f24fc1 --hash=sha256:6fe49a60b25b584e2f4ef175b29d3a83ba63b3a4df1b4c0605b826668d1b6be5 --hash=sha256:19a4b72a6ae5bb467fea018b825f0a7d917789bcfe893e53f15c92805d187294 --hash=sha256:9fe92406c857409b70a38729dbdf6578caf9228de0aef5bc44f859ffe971a39e --hash=sha256:c9457fa5c121e94a58d6505cadca8bed1c64444b83b3204928a866ca2e599105 --hash=sha256:74a015102e877d0ccd02cdeaa18b32aa7273746914a6c5d0456dd442cb65b99c --hash=sha256:ff032765bb8716d9387fd5376d987a937254b0619eff0972779515b5c98820bc --hash=sha256:a595c12c618119255c90deb4b046e1ca3bcfad64667c43d1166f2b04bc72db09 --hash=sha256:69361315039878c0680be456640f8705d76cb4a3a3fe1e057e0f261b74be4b31 --hash=sha256:0b0069c752ec14172c5f78208f1863d7ad6755a6fae6fe76ec2c80d13be41e42 --hash=sha256:a190f2a5dbbdbff4b74e3103cef44344bc30e61255beb27310e2aec407766052 --hash=sha256:5432dd7b34107ae8ed6c10a71b4397f1c853bd39a4d6ffa7e35f40584cffd161 --hash=sha256:cb93f6b2ab0f6853550b74e051d297c27a638719753eb9ff66d1e4072be67133 --hash=sha256:763669a367869786bb4c8fcf731f4175775a5b43f070f50f46f0b59da45375d0! Will try again.
An error occurred while installing cffi==1.14.1 --hash=sha256:8416ed88ddc057bab0526d4e4e9f3660f614ac2394b5e019a628cdfff3733849 --hash=sha256:d6033b4ffa34ef70f0b8086fd4c3df4bf801fee485a8a7d4519399818351aa8e --hash=sha256:4fa72a52a906425416f41738728268072d5acfd48cbe7796af07a923236bcf96 --hash=sha256:4ce1e995aeecf7cc32380bc11598bfdfa017d592259d5da00fc7ded11e61d022 --hash=sha256:f90c2267101010de42f7273c94a1f026e56cbc043f9330acd8a80e64300aba33 --hash=sha256:6923d077d9ae9e8bacbdb1c07ae78405a9306c8fd1af13bfa06ca891095eb995 --hash=sha256:b1d6ebc891607e71fd9da71688fcf332a6630b7f5b7f5549e6e631821c0e5d90 --hash=sha256:66dd45eb9530e3dde8f7c009f84568bc7cac489b93d04ac86e3111fb46e470c2 --hash=sha256:cda422d54ee7905bfc53ee6915ab68fe7b230cacf581110df4272ee10462aadc --hash=sha256:d3148b6ba3923c5850ea197a91a42683f946dba7e8eb82dfa211ab7e708de939 --hash=sha256:b2a2b0d276a136146e012154baefaea2758ef1f56ae9f4e01c612b0831e0bd2f --hash=sha256:ddff0b2bd7edcc8c82d1adde6dbbf5e60d57ce985402541cd2985c27f7bec2a0 --hash=sha256:26f33e8f6a70c255767e3c3f957ccafc7f1f706b966e110b855bfe944511f1f9 --hash=sha256:a6d28e7f14ecf3b2ad67c4f106841218c8ab12a0683b1528534a6c87d2307af3 --hash=sha256:4a03416915b82b81af5502459a8a9dd62a3c299b295dcdf470877cb948d655f2 --hash=sha256:4f53e4128c81ca3212ff4cf097c797ab44646a40b42ec02a891155cd7a2ba4d8 --hash=sha256:3cd2c044517f38d1b577f05927fb9729d3396f1d44d0c659a445599e79519792 --hash=sha256:bac0d6f7728a9cc3c1e06d4fcbac12aaa70e9379b3025b27ec1226f0e2d404cf --hash=sha256:267adcf6e68d77ba154334a3e4fc921b8e63cbb38ca00d33d40655d4228502bc --hash=sha256:892daa86384994fdf4856cb43c93f40cbe80f7f95bb5da94971b39c7f54b3a9c --hash=sha256:e23cb7f1d8e0f93addf0cae3c5b6f00324cccb4a7949ee558d7b6ca973ab8ae9 --hash=sha256:833401b15de1bb92791d7b6fb353d4af60dc688eaa521bd97203dcd2d124a7c1 --hash=sha256:f960375e9823ae6a07072ff7f8a85954e5a6434f97869f50d0e41649a1c8144f --hash=sha256:98be759efdb5e5fa161e46d404f4e0ce388e72fbf7d9baf010aff16689e22abe --hash=sha256:c991112622baee0ae4d55c008380c32ecfd0ad417bcd0417ba432e6ba7328caa --hash=sha256:effd2ba52cee4ceff1a77f20d2a9f9bf8d50353c854a282b8760ac15b9833168 --hash=sha256:fcf32bf76dc25e30ed793145a57426064520890d7c02866eb93d3e4abe516948 --hash=sha256:b87dfa9f10a470eee7f24234a37d1d5f51e5f5fa9eeffda7c282e2b8f5162eb1! Will try again.
Looking in indexes: https://pypi.org/simple/
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
An error occurred while installing cryptography==3.0 --hash=sha256:bec7568c6970b865f2bcebbe84d547c52bb2abadf74cefce396ba07571109c67 --hash=sha256:0c608ff4d4adad9e39b5057de43657515c7da1ccb1807c3a27d4cf31fc923b4b --hash=sha256:dea0ba7fe6f9461d244679efa968d215ea1f989b9c1957d7f10c21e5c7c09ad6 --hash=sha256:bea0b0468f89cdea625bb3f692cd7a4222d80a6bdafd6fb923963f2b9da0e15f --hash=sha256:8ecef21ac982aa78309bb6f092d1677812927e8b5ef204a10c326fc29f1367e2 --hash=sha256:0cbfed8ea74631fe4de00630f4bb592dad564d57f73150d6f6796a24e76c76cd --hash=sha256:124af7255ffc8e964d9ff26971b3a6153e1a8a220b9a685dc407976ecb27a06a --hash=sha256:45741f5499150593178fc98d2c1a9c6722df88b99c821ad6ae298eff0ba1ae71 --hash=sha256:4b9303507254ccb1181d1803a2080a798910ba89b1a3c9f53639885c90f7a756 --hash=sha256:384d7c681b1ab904fff3400a6909261cae1d0939cc483a68bdedab282fb89a07 --hash=sha256:4d355f2aee4a29063c10164b032d9fa8a82e2c30768737a2fd56d256146ad559 --hash=sha256:8ecf9400d0893836ff41b6f977a33972145a855b6efeb605b49ee273c5e6469f --hash=sha256:51e40123083d2f946794f9fe4adeeee2922b581fa3602128ce85ff813d85b81f --hash=sha256:9367d00e14dee8d02134c6c9524bb4bd39d4c162456343d07191e2a0b5ec8b3b --hash=sha256:a09fd9c1cca9a46b6ad4bea0a1f86ab1de3c0c932364dbcf9a6c2a5eeb44fa77 --hash=sha256:ce82cc06588e5cbc2a7df3c8a9c778f2cb722f56835a23a68b5a7264726bb00c --hash=sha256:ab49edd5bea8d8b39a44b3db618e4783ef84c19c8b47286bf05dfdb3efb01c83 --hash=sha256:8e924dbc025206e97756e8903039662aa58aa9ba357d8e1d8fc29e3092322053 --hash=sha256:8713ddb888119b0d2a1462357d5946b8911be01ddbf31451e1d07eaa5077a261! Will try again.
An error occurred while installing pynacl==1.4.0 --hash=sha256:54e9a2c849c742006516ad56a88f5c74bf2ce92c9f67435187c3c5953b346505 --hash=sha256:757250ddb3bff1eecd7e41e65f7f833a8405fede0194319f87899690624f2122 --hash=sha256:ea6841bc3a76fa4942ce00f3bda7d436fda21e2d91602b9e21b7ca9ecab8f3ff --hash=sha256:06cbb4d9b2c4bd3c8dc0d267416aaed79906e7b33f114ddbf0911969794b1cc4 --hash=sha256:537a7ccbea22905a0ab36ea58577b39d1fa9b1884869d173b5cf111f006f689f --hash=sha256:cd401ccbc2a249a47a3a1724c2918fcd04be1f7b54eb2a5a71ff915db0ac51c6 --hash=sha256:f8851ab9041756003119368c1e6cd0b9c631f46d686b3904b18c0139f4419f80 --hash=sha256:9c4a7ea4fb81536c1b1f5cc44d54a296f96ae78c1ebd2311bd0b60be45a48d96 --hash=sha256:2fe0fc5a2480361dcaf4e6e7cea00e078fcda07ba45f811b167e3f99e8cff574 --hash=sha256:30f9b96db44e09b3304f9ea95079b1b7316b2b4f3744fe3aaecccd95d547063d --hash=sha256:8122ba5f2a2169ca5da936b2e5a511740ffb73979381b4229d9188f6dcb22f1f --hash=sha256:7c6092102219f59ff29788860ccb021e80fffd953920c4a8653889c029b2d420 --hash=sha256:7757ae33dae81c300487591c68790dfb5145c7d03324000433d9a2c141f82af7 --hash=sha256:11335f09060af52c97137d4ac54285bcb7df0cef29014a1a4efe64ac065434c4 --hash=sha256:d452a6746f0a7e11121e64625109bc4468fc3100452817001dbe018bb8b08514 --hash=sha256:511d269ee845037b95c9781aa702f90ccc36036f95d0f31373a6a79bd8242e25! Will try again.
Installing initially failed dependencies…
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 252, in install
[InstallError]:       site_packages=state.site_packages
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2063, in do_install
[InstallError]:       keep_outdated=keep_outdated
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1313, in do_init
[InstallError]:       pypi_mirror=pypi_mirror,
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 900, in do_install_dependencies
[InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Looking in indexes: https://pypi.org/simple/
[pipenv.exceptions.InstallError]: Collecting bcrypt==3.1.7
[pipenv.exceptions.InstallError]:   Using cached bcrypt-3.1.7.tar.gz (42 kB)
[pipenv.exceptions.InstallError]: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
ERROR: Couldn't install package: bcrypt
 Package installation failed...
ERROR: Service 'blogproject_local' failed to build: The command '/bin/sh -c pipenv install --system --dev --ignore-pipfile' returned a non-zero code: 1
[arch@archlinux django-blog-project]$

**Comment by marklove5102** [comment]
arch系列最新

**Comment by zmrenwu** [comment]
似乎是 pipenv 安装 bcrypt 时出错了，我去验证一下在 macos 和 windows 上有没有这个问题。

**Comment by zmrenwu** [comment]
docker 镜像已经更新，请重新拉取一下最新的代码试一下呢？如果仍然有问题，请随时重开 issue 或者直接联系我。

**Comment by marklove5102** [comment]
放弃了在arch 搞这个。  
新的问题又出来了

**Comment by marklove5102** [comment]
![捕获](https://user-images.githubusercontent.com/12666917/95863307-9cb07e80-0d96-11eb-8040-4f0190206057.PNG)
